name: Go CI

on:
  push:
    branches: [ iter25 ]
  pull_request:
    branches: [ iter25 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'  # Укажите вашу версию Go

      - name: Install dependencies
        run: go mod tidy


      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          grep -vE "(mock.go|main.go|docs.go|alias.go|pb.go|noexit.go|revive.go)" coverage.out > coverage.filtered.out
          go tool cover -func=coverage.filtered.out

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: coverage.filtered.out
          token: ${{ secrets.CODECOV_TOKEN }}  # Используйте секрет для токена